### ISSUE TITLE
Commit of version 0.2.0 linked in Melpa is missing

### ISSUE THREAD

**Issue by sheijk** [crocket/dired-single#2]
This looks to be similar to #1 as the commit history zap seems to have removed the commit 27120d6a079541e994105e3f969032d3ae7edaa4 linked on the (Melpa Package)[https://stable.melpa.org/#/dired-single] and the tag for it.

Downloading and installing 0.2.0 from Melpa still works as it seems to download the (file from Melpa)[https://stable.melpa.org/packages/dired-single-0.2.0.el]. But installing dired-single from Nix will fail, see nix-community/emacs-overlay#179

**Comment by crocket** [comment]
I will release 0.3.0, then.

**Comment by crocket** [comment]
I just released 0.3.0. Does it fix the issue?

**Comment by sheijk** [comment]
Yes, now it works both using package.el and using nix+emacs-overlay, too. Thanks for the fix!
