### ISSUE TITLE
Release 0.2.0?

### ISSUE THREAD

**Issue by daviwil** [crocket/dired-single#4]
Hi @crocket!

Is there any chance you might be able to release version `0.2.0` of `dired-single`?  I'm currently trying to package up the library for the [GNU Guix](https://guix.gnu.org) distribution and I'd love to have the new `dired-single-up-directory` function from PR #3 included.

Thanks!

David

**Comment by crocket** [comment]
I will soon.

**Comment by crocket** [comment]
Done.
