### ISSUE TITLE
emacsclient closes when editing directory

### ISSUE THREAD

**Issue by AndreaOrru** [crocket/dired-single#7]
I use an Emacs server I connect to using `emacsclient`.

If I try to edit the current directory with `emacsclient -t .` and navigate around with `dired`, the client gets killed, presumably because the original buffer is no longer there (because of `dired-single` behaviour).

Do you know of any workarounds?

**Comment by crocket** [comment]
I wish I knew. I am not very good at emacs lisp.

**Comment by AndreaOrru** [comment]
It's not really a solution, but I'm doing `alias "e."="emacsclient -t . .."` which will open one more buffer and prevent Emacs from killing the frame.

**Comment by crocket** [comment]
I think dired-single was not designed to work with emacsclient.
`dired-single-buffer` calls `find-alternate-file` if the cursor is on a directory. `find-alternate-file` kills the current buffer and opens the chosen directory in a new buffer.

**Comment by crocket** [comment]
Can you find alternatives to using emacsclient to view a directory?

**Comment by crocket** [comment]
I think you better use a terminal file manager like `lf`.

**Comment by crocket** [comment]
Closing this because I can't solve this issue and this issue has been open for too long.
